- pgcommitfest/commitfest/views.py
After [this refactor](https://github.com/JelteF/commitfest/commit/a173224a3c4159e03ce554b3a92e66253be5e67b) of the patch URL, when you create a patch, you're still redirected to the old patch URL, which no longer exists.
> Fix redirect to patch edit page on creation

- pgcommitfest/commitfest/admin.py
- pgcommitfest/commitfest/fixtures/commitfest_data.json
- pgcommitfest/commitfest/models.py
This adds some basic functionality to allow making changes to the CFBot integration locally, without having to push to prod/staging. To do so this adds the CFBot integration tables to the admin panel and adds some dummy CFBot data to our dummy development dataset. One somewhat interesting thing this required that now the `CfbotBranch` has an overridden `save` method, which stores `NULL` in the commit_id if an empty string is saved. This only impacts the save behaviour of the Django admin interface because the webhook that the actual CFBot calls bypasses the Django models and inserts directly into the underlying tables.
> Support local cfbot integration development with dummy data

- pgcommitfest/commitfest/forms.py
- pgcommitfest/commitfest/views.py
People sometimes forget to configure the author field when adding a patch to the commitfest. It's also kinda silly to always have to search for your own name. In the cases that people add commitfest entries for patches of others, removing themselves and adding the other person is only a backspace presses away.
Apart from that this also updates the patch creation form to include all the fields from the patch edit form. Instead of having the patch creation submit button redirect to the patch edit page.
Fixes #14
> Default author to self when adding a new patch

- .github/workflows/ci.yaml
- Makefile
- biome.json
- media/commitfest/css/commitfest.css
- media/commitfest/js/commitfest.js
Similarly to #1 but now for the frontend languages.
> Autoformat js and css

- media/commitfest/js/commitfest.js
- pgcommitfest/commitfest/templates/base_form.html
It's a bit silly that you have to manually enter something in the description, when you just selected a thing with that title from the thread search modal. So this starts auto-filling the description. This only happens when the field is empty, and will strip some common prefixes like `Re:` and `[PATCH]`.  
Fixes #16
> Autofill new patch description based on selected thread

- media/commitfest/js/commitfest.js
- pgcommitfest/commitfest/templates/commitfest.html
- pgcommitfest/commitfest/views.py
Implements reverse sorting in the columns of the commitfest pages.
This is a cleaned up version of #28 and #32
Fixes #20
> Add reverse sorting on commitfest page

- pgcommitfest/commitfest/forms.py
- pgcommitfest/commitfest/models.py
Many people assign themselves to open entries as a reviewer/committer as a sort of bookmarking system for open patches they are interested in. Currently it's allowed for others to assign anyone as a reviewer/committer, thus effectively modifying people their bookmarking system. This is especially made worse because you can sign up in your profile to receive email updates from the commitfest app for patches that you are reviewer/committer of and would then thus start receiving updates for patches you might not be interested in.
Assigning reviewers/committers to closed patches is still be allowed. When committing, reviewers are sometimes added by the committer to reflect the same as their Reviewed-By footer, even if those reviewers didn't explicitly sign up as a reviewer on the commitfest …
> Disallow assigning others as reviewer/committer on open patches

- pgcommitfest/commitfest/views.py
Some people have account names that do not look like their names. This allows people to identify committers based on their regular name on the commitfest page.
> Show committer name in commitfest list

- requirements.txt
These libraries were unused. We only used the APIs from `pycryptodomex`.
Fixes #43
> Remove pycrypto and pycryptodome from requirements.txt

- media/commitfest/css/commitfest.css
This fixes an issue I reported on the pgsql-www mailing list [1].
The checkboxes that were present on the review form were not displayed correctly. This makes some small css tweaks to address that problem. A better fix would probably be to generate different HTML, but that would require changing the way forms are rendered by Django for these checkboxes. Which is not trivial to do. So for now this fix is fine.
Before:
After:
[1]: https://www.postgresql.org/message-id/flat/CADXhmgQbed%2BJP3o5szv15sKsT5gkfZi4urOSLsYoC-oAGepK7g%40mail.gmail.com
> Fix review form checkbox styling

- pgcommitfest/commitfest/templates/commitfest.html
- pgcommitfest/commitfest/views.py
If things take too long, then CFBot will mark the build as timed out.
Such builds would not have that "timeout" status reflected correctly,
and would be displayed as running forever.
Fixes #39
> Show a CI timeout as a failure

- .github/workflows/ci.yaml
- Makefile
- dev_requirements.txt
- pgcommitfest/commitfest/templates/404.html
- pgcommitfest/commitfest/templates/activity.html
- pgcommitfest/commitfest/templates/base.html
- pgcommitfest/commitfest/templates/base_form.html
- pgcommitfest/commitfest/templates/commitfest.html
- pgcommitfest/commitfest/templates/home.html
- pgcommitfest/commitfest/templates/patch.html
- pgcommitfest/commitfest/templates/patchsearch.html
- pgcommitfest/commitfest/templates/report_authors.html
- pgcommitfest/userprofile/templates/userprofileform.html
We were already autoformatting Python, Javascript and CSS. This starts doing the same for our Django HTML templates.
> Autoindent django templates using djhtml

- pgcommitfest/commitfest/templates/commitfest.html
- pgcommitfest/commitfest/views.py
Having both "Latest email" and "Latest activity" as a column on the commitfest page is kind of useless. The "Latest activity" often is simply the date that a patch was moved to the next commitfest, so it's content is rather useless in general. If we improve the commitfest app to contain more useful info, then it might become more useful to have this timestamp. For now it seems fine to remove it though. We can always add it back later if it turns out that people miss it.
Fixes #21
> Remove latest activity column

- pgcommitfest/commitfest/templates/commitfest.html
Exact dates of the last email are usually not super useful when looking at the commitfest page. This instead starts showing a relative time since. For the rare cases where the exact date & time is needed, the tooltip will show the exact date & time. When this gets deployed to prod a small change also needs to be made to the cfbot, because this breaks the cfbot its html scraping.
> Show "Latest email" column as a relative time

- media/commitfest/css/commitfest.css
- pgcommitfest/commitfest/forms.py
- pgcommitfest/commitfest/models.py
- pgcommitfest/commitfest/templates/archive.html
- pgcommitfest/commitfest/templates/base.html
- pgcommitfest/commitfest/templates/home.html
- pgcommitfest/commitfest/templatetags/commitfest.py
- pgcommitfest/commitfest/views.py
- pgcommitfest/urls.py
The homepage was not showing a lot of useful information. It had a list of mostly ancient commitfests, a search box, and a few links to more useful pages. This revamps the homepage with an initial version of a personalized dashboard. The dashboard shows patches that the user is subscribed to, either because they are marked as an author or a reviewer. We then try to group and sort these patches in an attempt to let the user easily find the patches that require their attention.
Many things can likely be tweaked/improved. I think this first version is already a huge improvement over the status quo, so I think it's worth committing deploying this mostly as is and then iterating on it based on feedback.
This is what it looks like:
Fixes #36
> Revamp the homepage to show you patches you might be interested in

- pgcommitfest/userprofile/views.py
This solves the issue #56, as that seems to be caused by a lack of "title" field in template parameters in:
https://github.com/postgres/pgcommitfest/blob/main/pgcommitfest/commitfest/templates/base.html#L17-L25
Fixes #56
> Provide a title to the profile edit screen

- pgcommitfest/commitfest/templates/me.html
- pgcommitfest/commitfest/views.py
Added stats generally visible on the generic commitfest page to the personal dashboard.
> enhancement: added commitfest stats to /me page

- .editorconfig
HTML template subcomponent filenames get prefixed with .inc but are just html-like files and thus have the same layout enforced as .html files.
> Add .inc files to .editorconfig

- media/commitfest/js/commitfest.js
- pgcommitfest/commitfest/templates/base.html
- pgcommitfest/commitfest/templates/base_form.html
- pgcommitfest/commitfest/templates/commitfest.html
- pgcommitfest/commitfest/templates/me.html
- pgcommitfest/commitfest/templates/patch.html
- pgcommitfest/commitfest/templates/selectize_css.html
- pgcommitfest/commitfest/templates/selectize_js.html
- pgcommitfest/commitfest/views.py
The select box for selecting a committer of a patch was kinda hard to
use. This fixes it in two ways:
1. Sorts names by first names, instead of last names. This way the list
actually looks ordered.
2. Use Selectize to make the select box searchable.
To make such a change to selectize simpler in the future this starts
including the selectize css/js on every page and adds a simple
"enable-selectize" class that can be used to easily enable selectize on
any select box.
> Make committer select box easier to use

- pgcommitfest/commitfest/views.py
Draft patches would show up as requiring moving to a next commitfest.
That's incorrect, they are fine where they are.
Closes #78
> Show draft patches in the correct section in the personal dashboard

- pgcommitfest/commitfest/templates/commitfest.html
- pgcommitfest/commitfest/templates/home.html
- pgcommitfest/commitfest/views.py
Use new icons for sorting up and down. Also fix bug where homepage would
show empty dashboard after sorting the same column three times.
> Improve sorting
